#!/usr/bin/env bash
set -u
OUT="$(cd "$(dirname "$0")" && pwd)/papers"
mkdir -p "$OUT"
FAIL="$(cd "$(dirname "$0")" && pwd)/failures.txt"
: > "$FAIL"
echo "[1/13] Reinforcement Learning Based Symbolic Regression for Load Modeling"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://arxiv.org/pdf/2503.06879" -o "$OUT/01_2026_Reinforcement Learning Based Symbolic Regression for Load Modeling.pdf" || echo "Reinforcement Learning Based Symbolic Regression for Load Modeling" >> "$FAIL"
echo "[2/13] Symbolic Equation Modeling of Composite Loads: A Kolmogorov-Arnold Network based Learning Approach"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://arxiv.org/pdf/2508.19612" -o "$OUT/02_2025_Symbolic Equation Modeling of Composite Loads_ A Kolmogorov-Arnold Network based Learning Approach.pdf" || echo "Symbolic Equation Modeling of Composite Loads: A Kolmogorov-Arnold Network based Learning Approach" >> "$FAIL"
echo "[3/13] 基于动态响应特征学习的综合负荷模型构成在线辨识"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://epjournal.csee.org.cn/rc-pub/front/front-article/download/153308078/lowqualitypdf/%E5%9F%BA%E4%BA%8E%E5%8A%A8%E6%80%81%E5%93%8D%E5%BA%94%E7%89%B9%E5%BE%81%E5%AD%A6%E4%B9%A0%E7%9A%84%E7%BB%BC%E5%90%88%E8%B4%9F%E8%8D%B7%E6%A8%A1%E5%9E%8B%E6%9E%84%E6%88%90%E5%9C%A8%E7%BA%BF%E8%BE%A8%E8%AF%86.pdf" -o "$OUT/03_2026_基于动态响应特征学习的综合负荷模型构成在线辨识.pdf" || echo "基于动态响应特征学习的综合负荷模型构成在线辨识" >> "$FAIL"
echo "[4/13] Diffusion model-based parameter estimation in dynamic power systems"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://www.nature.com/articles/s44172-026-00670-z.pdf" -o "$OUT/04_2026_Diffusion model-based parameter estimation in dynamic power systems.pdf" || echo "Diffusion model-based parameter estimation in dynamic power systems" >> "$FAIL"
echo "[5/13] Online modeling method for composite load model including EVs and battery storage based on measurement data"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://www.frontiersin.org/journals/energy-research/articles/10.3389/fenrg.2024.1378067/pdf" -o "$OUT/05_2024_Online modeling method for composite load model including EVs and battery storage based on measurement data.pdf" || echo "Online modeling method for composite load model including EVs and battery storage based on measurement data" >> "$FAIL"
echo "[6/13] Dynamic equivalent modelling for active distributed network considering adjustable loads charging characteristics"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://ietresearch.onlinelibrary.wiley.com/doi/pdfdirect/10.1049/gtd2.13344" -o "$OUT/06_2024_Dynamic equivalent modelling for active distributed network considering adjustable loads charging characteristics.pdf" || echo "Dynamic equivalent modelling for active distributed network considering adjustable loads charging characteristics" >> "$FAIL"
echo "[7/13] Dynamic Equivalence of Active Distribution Network: Multiscale and Multimodal Fusion Deep Learning Method with Automatic Parameter Tuning"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://www.mdpi.com/2227-7390/13/19/3213/pdf?download=1" -o "$OUT/07_2025_Dynamic Equivalence of Active Distribution Network_ Multiscale and Multimodal Fusion Deep Learning Method with Automatic Parameter Tuni.pdf" || echo "Dynamic Equivalence of Active Distribution Network: Multiscale and Multimodal Fusion Deep Learning Method with Automatic Parameter Tuning" >> "$FAIL"
echo "[8/13] Noise Amplitude in Ambient PMU Data and its Impact on Load Models Identification"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://latamt.ieeer9.org/index.php/transactions/article/download/8878/2449/113533" -o "$OUT/08_2024_Noise Amplitude in Ambient PMU Data and its Impact on Load Models Identification.pdf" || echo "Noise Amplitude in Ambient PMU Data and its Impact on Load Models Identification" >> "$FAIL"
echo "[9/13] Applications of Electrical Load Modelling in Digital Twins of Power Systems"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://mdpi-res.com/d_attachment/energies/energies-18-00775/article_deploy/energies-18-00775.pdf" -o "$OUT/09_2025_Applications of Electrical Load Modelling in Digital Twins of Power Systems.pdf" || echo "Applications of Electrical Load Modelling in Digital Twins of Power Systems" >> "$FAIL"
echo "[10/13] 面向新型电力系统的负荷模型研究综述"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://www.dlbh.net/dlbh/article/pdf/240390" -o "$OUT/10_2025_面向新型电力系统的负荷模型研究综述.pdf" || echo "面向新型电力系统的负荷模型研究综述" >> "$FAIL"
echo "[11/13] Data Centre Model for Transient Stability Analysis of Power Systems"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://arxiv.org/pdf/2505.16575" -o "$OUT/11_2026_Data Centre Model for Transient Stability Analysis of Power Systems.pdf" || echo "Data Centre Model for Transient Stability Analysis of Power Systems" >> "$FAIL"
echo "[12/13] Dynamic Load Model for Data Centers with Pattern-Consistent Calibration"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://arxiv.org/pdf/2602.07859" -o "$OUT/12_2026_Dynamic Load Model for Data Centers with Pattern-Consistent Calibration.pdf" || echo "Dynamic Load Model for Data Centers with Pattern-Consistent Calibration" >> "$FAIL"
echo "[13/13] Dynamic Modeling of Data-Center Power Delivery for Power System Resonance Analysis"
curl -L --fail --retry 2 -A "Mozilla/5.0" "https://arxiv.org/pdf/2604.06624" -o "$OUT/13_2026_Dynamic Modeling of Data-Center Power Delivery for Power System Resonance Analysis.pdf" || echo "Dynamic Modeling of Data-Center Power Delivery for Power System Resonance Analysis" >> "$FAIL"
echo "Done. PDF folder: $OUT"